version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./SimpleServer
    ports:
      - "8080:8080"
