global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend1:8080', 'backend2:8080']
    metrics_path: /actuator/prometheus