{
 "title": "통합모니터링",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nginx request 부하",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "backend2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"backend2:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"backend1:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}